// <auto-generated />
namespace LivescoreRest.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Game : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Game));
        
        string IMigrationMetadata.Id
        {
            get { return "201505191253129_Game"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
